# Generated by Django 4.2.4 on 2023-09-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_category_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categories',
        ),
    ]
